server:
  port: 9000
spring:
  application:
    name: fuchuang-gateway-service
  profiles:
    #active: aggregation
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 123.56.125.48:8848
        namespace: a848affe-38dc-4801-bb04-70ad47876920