spring:
  cloud:
    gateway:
      routes:
        - id: fuchuang-user-service
          uri: lb://fuchuang-user-service/api/user-service/**
          predicates:
            - Path=/api/user-service/**
          filters:
            - name: TokenValidate
              args:
                blackPathPre:
                  - /api/user-service/logout
                  - /api/user-service/deletion
                  - /api/user-service/v1/user